In [1397]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 2C28-A088

 Directory of C:\Users\Mewandi\Desktop\AI_Projects\Job_Recommendation_Engine

08/18/2025  02:35 PM    <DIR>          .
08/18/2025  02:35 PM    <DIR>          ..
08/18/2025  11:15 AM    <DIR>          .ipynb_checkpoints
08/05/2025  12:58 PM            20,878 education.csv
08/05/2025  12:58 PM           641,984 employment.csv
08/03/2025  11:36 PM           221,690 Explination.jpeg
08/05/2025  12:58 PM           349,053 jobs.csv
08/18/2025  02:35 PM            58,208 MultinomialNB.ipynb
08/18/2025  11:12 AM            44,567 Untitled-Copy1.ipynb
08/15/2025  11:41 AM               337 Using CNN.ipynb
               7 File(s)      1,336,717 bytes
               3 Dir(s)  509,209,374,720 bytes free

In [1398]:
import numpy as np
import pandas as pd

In [1399]:
job_df = pd.read_csv("jobs.csv")

job_df.columns

Index(['jobTitle', 'position', 'minBudget', 'maxBudget', 'travelReq',
       'location', 'description', 'attachment', 'orgId', 'jobType', 'skills',
       'recruiter', 'client', 'minExp', 'maxExp', 'noticePeriod', 'status',
       'jobId', 'createDate', 'vacancies', 'priority', 'priceType', 'workType',
       'comment', 'subvendorId', 'Questionnaires', 'country', 'department',
       'eligibility', 'responsibilities'],
      dtype='object')

In [1400]:
100 * job_df.isnull().sum() / len(job_df)

jobTitle              0.000000
position              0.000000
minBudget             0.325733
maxBudget             0.325733
travelReq             0.000000
location              0.000000
description           0.000000
attachment           77.850163
orgId                 0.000000
jobType               0.000000
skills                0.000000
recruiter             0.000000
client                0.000000
minExp                0.000000
maxExp                0.000000
noticePeriod          0.000000
status                0.000000
jobId                 0.000000
createDate            0.000000
vacancies            12.052117
priority             14.657980
priceType            16.286645
workType             15.635179
comment              98.371336
subvendorId         100.000000
Questionnaires      100.000000
country              95.114007
department          100.000000
eligibility         100.000000
responsibilities    100.000000
dtype: float64

#### IDs, duplicates, or any column with >95% missing values

In [1401]:
job_df = job_df.drop(columns=['comment'])
job_df = job_df.drop(columns=['subvendorId']) 
job_df = job_df.drop(columns=['Questionnaires']) 
job_df = job_df.drop(columns=['country']) 
job_df = job_df.drop(columns=['department']) 
job_df = job_df.drop(columns=['eligibility']) 
job_df = job_df.drop(columns=['responsibilities']) 
job_df = job_df.drop(columns=['orgId']) 
job_df = job_df.drop(columns=['jobId'])
job_df = job_df.drop(columns=['client'])

In [1402]:
job_df.columns

Index(['jobTitle', 'position', 'minBudget', 'maxBudget', 'travelReq',
       'location', 'description', 'attachment', 'jobType', 'skills',
       'recruiter', 'minExp', 'maxExp', 'noticePeriod', 'status', 'createDate',
       'vacancies', 'priority', 'priceType', 'workType'],
      dtype='object')

In [1403]:
job_df.head(1)

,jobTitle,position,minBudget,maxBudget,travelReq,location,description,attachment,jobType,skills,recruiter,minExp,maxExp,noticePeriod,status,createDate,vacancies,priority,priceType,workType
0,Plant Maintenance Engineer,Plant Maintenance Engineer,300000.0,600000.0,True,{Hyderabad},"Read and understand the data from P&ID, PEFS, ...",NaN,Permanent,"{""Plant Maintenance""}",DB413862,2.0,5.0,15-30 days,Active,2023-01-31 11:09:26.36189,2.0,High,INR,Work from Office

In [1404]:
job_df.corr(numeric_only=True)['minBudget']

minBudget    1.000000
maxBudget    0.842138
travelReq    0.092756
minExp       0.038783
maxExp       0.037647
vacancies   -0.007996
Name: minBudget, dtype: float64

In [1405]:
job_df.columns.duplicated()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [1406]:
job_col_df = job_df[['jobTitle', 'description', 'status', 'skills']]
#job_col_df

### Employ chossing columns

In [1407]:
emp_df = pd.read_csv("employment.csv")

emp_df.columns

Index(['employmentId', 'uploadResume', 'currentCompany', 'currentDesignation',
       'annualSalary', 'industry', 'functionalArea', 'role', 'currentLocation',
       'orgId', 'noticePeriod', 'skills', 'totalWorkExp', 'minExp', 'maxExp',
       'applicantId', 'preferedLocation', 'holdingAnyOffer', 'expectedCtc',
       'feedback', 'comment', 'isCurrent', 'companyEmail', 'packageOffered',
       'lastWorkingDay', 'remarks', 'previousCompany', 'offerLetter',
       'experienceLetter', 'relieveingLetter', 'isRecent', 'paySlips',
       'createdOn'],
      dtype='object')

In [1408]:
emp_df = emp_df.drop(columns=['employmentId'])
emp_df = emp_df.drop(columns=['applicantId'])
emp_df = emp_df.drop(columns=['orgId'])

In [1409]:
100 * emp_df.isnull().sum() / len(emp_df)

uploadResume           23.773225
currentCompany          4.621248
currentDesignation      2.048595
annualSalary            5.002382
industry                4.525965
functionalArea          5.383516
role                  100.000000
currentLocation         4.764173
noticePeriod            8.575512
skills                  0.000000
totalWorkExp            4.621248
minExp                100.000000
maxExp                100.000000
preferedLocation       26.822296
holdingAnyOffer        27.870414
expectedCtc            26.679371
feedback               98.999524
comment                92.424964
isCurrent              43.163411
companyEmail           66.936636
packageOffered         99.285374
lastWorkingDay         98.999524
remarks                97.189138
previousCompany       100.000000
offerLetter           100.000000
experienceLetter      100.000000
relieveingLetter      100.000000
isRecent              100.000000
paySlips              100.000000
createdOn               0.000000
dtype: float64

In [1410]:
emp_df.head(2)

,uploadResume,currentCompany,currentDesignation,annualSalary,industry,functionalArea,role,currentLocation,noticePeriod,skills,...,packageOffered,lastWorkingDay,remarks,previousCompany,offerLetter,experienceLetter,relieveingLetter,isRecent,paySlips,createdOn
0,NaN,ESMOB Technologies,React JS Developer,3.5,1.0,Software Developer,NaN,Hyderabad,NaN,"{css,js}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-08 08:49:43.960932
1,NaN,Lejara Global IT Solutions Pvt. Ltd,RPA Developer,4.5,1.0,Software Developer,NaN,Hyderabad,NaN,"{RPA,python}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-08 08:49:43.960932

In [1411]:
emp_cols_df = emp_df[['functionalArea', 'skills']]

### Education chossing columns

In [1412]:
edu_df = pd.read_csv("education.csv")

edu_df.columns

Index(['Id', 'primarySchool', 'primaryPercentage', 'primaryPassoutYear',
       'secondarySchool', 'secondaryPercentage', 'secondaryPassoutYear',
       'graduation', 'graduationPercentage', 'graduationPassoutYear', 'orgId',
       'applicantId', 'certificates', 'name', 'degree', 'fieldOfStudy',
       'percentage', 'certificate', 'createdOn'],
      dtype='object')

In [1413]:
edu_df = edu_df.drop(columns=['Id'])
edu_df = edu_df.drop(columns=['applicantId'])
edu_df = edu_df.drop(columns=['orgId'])

In [1414]:
edu_df.head(3)

,primarySchool,primaryPercentage,primaryPassoutYear,secondarySchool,secondaryPercentage,secondaryPassoutYear,graduation,graduationPercentage,graduationPassoutYear,certificates,name,degree,fieldOfStudy,percentage,certificate,createdOn
0,NaN,0,0,NaN,0.0,0,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-08 08:48:16.349684
1,Marks High school,86,1999,Marks High school,80.0,2001,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-08 08:48:16.349684
2,NaN,0,0,NaN,0.0,0,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-08 08:48:16.349684

In [1415]:
100 * edu_df.isnull().sum() / len(edu_df)

primarySchool             94.148936
primaryPercentage          0.000000
primaryPassoutYear         0.000000
secondarySchool           95.744681
secondaryPercentage        0.000000
secondaryPassoutYear       0.000000
graduation                95.212766
graduationPercentage       0.000000
graduationPassoutYear      0.000000
certificates              92.021277
name                     100.000000
degree                   100.000000
fieldOfStudy             100.000000
percentage               100.000000
certificate              100.000000
createdOn                  0.000000
dtype: float64

### Let's combine all datas to make one

In [1416]:
job_col_df.rename(columns={'skills': 'required_skills'}, inplace=True)
emp_cols_df.rename(columns={'skills': 'employee_skills'}, inplace=True)

C:\Users\Mewandi\AppData\Local\Temp\ipykernel_12388\1312139321.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  job_col_df.rename(columns={'skills': 'required_skills'}, inplace=True)
C:\Users\Mewandi\AppData\Local\Temp\ipykernel_12388\1312139321.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emp_cols_df.rename(columns={'skills': 'employee_skills'}, inplace=True)

In [1417]:
total_df = pd.concat([job_col_df, emp_cols_df])

In [1418]:
total_df = pd.DataFrame(total_df)

In [1419]:
100 * total_df.isnull().sum() / len(total_df)

jobTitle           87.240233
description        87.240233
status             87.240233
required_skills    87.240233
functionalArea     17.456359
employee_skills    12.759767
dtype: float64

In [1420]:
for i in total_df:
    total_df[i] = total_df[i].fillna(" ")

In [1421]:
100 * total_df.isnull().sum() / len(total_df)

jobTitle           0.0
description        0.0
status             0.0
required_skills    0.0
functionalArea     0.0
employee_skills    0.0
dtype: float64

In [1423]:
total_df.head(2)

,jobTitle,description,status,required_skills,functionalArea,employee_skills
0,Plant Maintenance Engineer,"Read and understand the data from P&ID, PEFS, ...",Active,"{""Plant Maintenance""}",,
1,Adobe Analytics developer,An understanding of the marketing technologies...,Active,"{""Adobe anaytics"",Agile,tableau,Marketo,""power...",,
2,AEM architect,"To analyze, understand the client’s business u...",Active,"{JIRA,Confluence,AEM}",,
3,Azure Administrator,1.\tArchitecture and Design for large scale Az...,Active,"{""Azure Administrator ""}",,
4,AEM architect,"Should have experience in java, OSGI, Componen...",Active,"{sling,jackrabbit,OSGI,felix,JCR}",,
5,Assistant Brand Manager,Classification: All - Finance / Accounts / Inv...,active,"{Sales,""Social Media Marketing"",Branding,""Digi...",,

In [1424]:
total_df['combined_cols'] = (   
                                total_df['description'] + " " +
                                total_df['status'] + " " +
                                total_df['required_skills'] + " " +
                                total_df['functionalArea'] + " " +
                                total_df['employee_skills']
                             )

In [1425]:
total_df['combined_cols'] = total_df['combined_cols'].fillna(" ")

In [1427]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

x_train = cv.fit_transform(total_df['combined_cols'])

In [1428]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(total_df['jobTitle'])
y_train

array([165,  16,  11, ...,   0,   0,   0])

In [1431]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train, y_train)
# y_pred = model.predict(x_test)

MultinomialNB()

In [1434]:
data = {
    'functionalArea': ['Computer Science'],
    'description': ['I understand computer languages and also, I solved many projects in AI and Machine Learning'],
    'status': ['Active'],
    'required_skills': ['computer languages'],
    'employee_skills': ['I am a programmer and I can do whatever you want'],
}
data = pd.DataFrame(data)

# combine columns in the same way as training
data['combined_cols'] = (
    data['description'] + " " +
    data['status'] + " " +
    data['required_skills'] + " " +
    data['functionalArea'] + " " +
    data['employee_skills']
)
data = data.fillna(" ")

# ✅ only transform, do NOT fit again
X_test = cv.transform(data['combined_cols'])

# ✅ predict
y_pred = model.predict(X_test)
print("Encoded prediction:", y_pred)

# Decode back to string
predicted_jobTitle = label_encoder.inverse_transform(y_pred)
print("Predicted jobTitle:", predicted_jobTitle[0])

Encoded prediction: [60]
Predicted jobTitle: Dot Net Developer